### ISSUE TITLE
Focused test with junit:consolidate gives "Fatal error: Cannot read property 'name' of undefined"

### ISSUE THREAD

**Issue by maddisondavid** [gruntjs/grunt-contrib-jasmine#195]
When junit is setup with the option consolidate:true, and a focused test is used, the tests run and the grunt task throws "Fatal error: Cannot read property 'name' of undefined" before the summary is written out.

I think the problem is that it attempts to use the name of Suite1 as the name of the Junit XML, but Suite1 is undefined.

Stack Trace : 
Fatal error: Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at writeJunitXml (/myProject/node_modules/grunt-contrib-jasmine/tasks/jasmine.js:397:80)
    at EventEmitter.<anonymous> (/myProject/node_modules/grunt-contrib-jasmine/tasks/jasmine.js:370:9)
    at EventEmitter.emit (/myProject/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
    at /myProject/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/lib/phantomjs.js:113:24
    at Array.some (native)
    at loopy [as _onTimeout] (/myProject/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/lib/phantomjs.js:101:33)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

**Comment by maddisondavid** [comment]
Slightly related to #192
