### ISSUE TITLE
Puppeteer doesn't find the _SpecRunner.html file generated.

### ISSUE THREAD

**Issue by jfarrelly-voysis** [gruntjs/grunt-contrib-jasmine#274]
Using `"grunt-contrib-jasmine": "^2.0.0"`, I get the following error when running `grunt jasmine`:
```
grunt test
Running "jasmine:src" (jasmine) task

Testing Jasmine specs via Headless Chrome
>> Error caught from Puppeteer
Warning: Error: net::ERR_FILE_NOT_FOUND at file:///my-project/node_modules/grunt-contrib-jasmine/_SpecRunner.html
  at navigate (/my-project/node_modules/puppeteer/lib/Page.js:539:37)
  at <anonymous>:null:null
  at process._tickCallback (internal/process/next_tick.js:188:7)
 Use --force to continue.

Aborted due to warnings.
```

My config in `Gruntfile.js` is:
```js
        jasmine: {
            src: 'src/js/*.js',
            options: {
                specs: 'spec/*.js'
            }
        }
```

`_SpecRunner.html` is still generated in the project root, but it seems that the plugin launches puppeteer with a path to the file inside the `grunt-config-jasmine` directory (which does not exist).

**Comment by sakshi87** [comment]
Hii @jfarrelly-voysis @vladikoff 

Using ```grunt-contrib-jasmine: ^2.1.0```, I got the following error when running ```npm install-test```:

```
> grunt test && tsc --noEmit ./test/type-test.ts
Running "jasmine:requirejs" (jasmine) task

Testing specs with Jasmine/latest via HeadlessChrome/77.0.3844.0

log: Failed to load resource: net::ERR_FILE_NOT_FOUND
```
My config in Gruntfile.js
```
        jasmine: {
            requirejs: {
                src: [],
                options: {
                    specs: 'test/*-test.js',
                    vendor: 'test/vendor/*.js',
                    helpers: 'test/*-helper.js',
                    template: require('grunt-template-jasmine-requirejs')
                }
            },
```
The issue is somewhat similar to the one you faced, it will be really helpful if you may suggest what I am missing here.
