### ISSUE TITLE
New rimraf version causing issue. 

### ISSUE THREAD

**Issue by mikerussellnz** [gruntjs/grunt-contrib-jasmine#310]
Hi

It appears the rimraf library has been updated and is being pulled in but the new version has some sort of syntax error.

09:17:16 [ERROR] node_modules/grunt-contrib-jasmine/node_modules/rimraf/rimraf.js:7
09:17:16 [ERROR] let glob = undefined
09:17:16 [ERROR] ^^^
09:17:16 [ERROR] 
09:17:16 [ERROR] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
09:17:16 [ERROR]     at exports.runInThisContext (vm.js:53:16)
09:17:16 [ERROR]     at Module._compile (module.js:387:25)
09:17:16 [ERROR]     at Object.Module._extensions..js (module.js:422:10)
09:17:16 [ERROR]     at Module.load (module.js:357:32)
09:17:16 [ERROR]     at Function.Module._load (module.js:314:12)
09:17:16 [ERROR]     at Module.require (module.js:367:17)
09:17:16 [ERROR]     at require (internal/module.js:20:19)
09:17:16 [ERROR]     at Object.<anonymous> (/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/fs-extra/lib/remove/index.js:1:76)
09:17:16 [ERROR]     at Module._compile (module.js:413:34)
09:17:16 [ERROR]     at Object.Module._extensions..js (module.js:422:10)

**Comment by mikerussellnz** [comment]
Probably outdated node version now that i think about it.
